pipeline {
    agent any

    tools {
        jdk 'jdk21' // Numele trebuie să coincidă cu cel din Jenkins > Global Tool Configuration
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
        GITHUB_CREDENTIALS = credentials("jenkins-token")
    }

    stages {

        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh "git fetch --tags"

                    def lastTag = sh(script: "git tag | sort --version-sort | tail -1", returnStdout: true).trim()
                    def parts = lastTag.tokenize('.')
                    def major = parts[0]
                    def minor = parts[1].toInteger()
                    def patch = parts[2]

                    env.IMAGE_TAG = "${major}.${minor + 1}.${patch}"
                    def username = env.DOCKER_CREDENTIALS_USR

                    sh "docker build -t ${username}/hello-img:${env.IMAGE_TAG} ."
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    def username = env.DOCKER_CREDENTIALS_USR
                    def password = env.DOCKER_CREDENTIALS_PSW

                    sh "echo ${password} | docker login -u ${username} --password-stdin"
                    sh "docker push ${username}/hello-img:${env.IMAGE_TAG}"

                    sh "git tag ${env.IMAGE_TAG}"

                    // push tag în remote
                    sh "git push https://${env.GITHUB_CREDENTIALS_USR}:${env.GITHUB_CREDENTIALS_PSW}@github.com/dorohoi-production-engineering/service.git ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Start containers') {
            steps {
                sh "IMAGE_TAG=${env.IMAGE_TAG} DOCKER_USERNAME=${env.DOCKER_CREDENTIALS_USR} docker compose up -d hello mongo"
            }
        }

        stage('Integration Tests') {
            steps {
                sh './gradlew testIT'
            }
        }
    }
}
