pipeline {
    agent any

    tools {
        jdk 'jdk21' // Numele trebuie să coincidă cu cel din Jenkins > Global Tool Configuration
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Tag image') {
            steps {
                script {
                    GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                    USERNAME = env.DOCKER_CREDENTIALS_USR
                }
                sh "docker build -t ${USERNAME}/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
            }
        }
        stage('Push image') {
            steps {
                script {
                    GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                    USERNAME = env.DOCKER_CREDENTIALS_USR
                    PASSWORD = env.DOCKER_CREDENTIALS_PSW
                }
                sh "echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin"
                sh "docker push ${USERNAME}/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"
            }
        }
    }
}
