pipeline {
    agent any

    tools {
        jdk 'jdk21' // Numele trebuie să coincidă cu cel din Jenkins > Global Tool Configuration
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
        GITHUB_CREDENTIALS = credentials("jenkins-token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Tag image') {
            steps {
                script {
                    GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    MAJOR_VERSION = sh([script: 'git tag | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                    MINOR_VERSION = sh([script: 'git tag | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                    PATCH_VERSION = sh([script: 'git tag | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                    USERNAME = env.DOCKER_CREDENTIALS_USR
                }
                sh "docker build -t ${USERNAME}/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
            }
        }
        stage('Push image') {
            steps {
                script {
                    sh "git fetch --tags"
                    lastTag = sh(script: 'git tag | tail -1', returnStdout: true).trim()
                    parts = lastTag.tokenize('.')
                    major = parts[0]
                    minor = parts[1].toInteger()
                    patch = parts[2]

                    newTag = "${major}.${minor + 1}.${patch}"
                    env.IMAGE_TAG = newTag

                    username = env.DOCKER_CREDENTIALS_USR
                    password = env.DOCKER_CREDENTIALS_PSW
                }

                sh "echo ${password} | docker login -u ${username} --password-stdin"
                sh "docker push ${username}/hello-img:${env.IMAGE_TAG}"
                sh "git tag ${env.IMAGE_TAG}"
                sh "git push https://${env.GITHUB_CREDENTIALS_USR}:${env.GITHUB_CREDENTIALS_PSW}@github.com/dorohoi-production-engineering/service.git ${env.IMAGE_TAG}"
            }
        }
        stage('Fetch image') {
            steps {
                sh "IMAGE_TAG=${env.IMAGE_TAG} DOCKER_USERNAME=${env.DOCKER_CREDENTIALS_USR} docker compose up -d hello mongo"
            }
        }
    }
}
